// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { Component, ComponentPublicInstance, computed, ComputedRef, createApp, customRef, defineAsyncComponent, defineComponent, DirectiveBinding, effectScope, EffectScope, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, getCurrentInstance, getCurrentScope, getCurrentWatcher, h, inject, InjectionKey, isProxy, isReactive, isReadonly, isRef, isShallow, markRaw, MaybeRef, MaybeRefOrGetter, nextTick, onActivated, onBeforeMount, onBeforeUnmount, onBeforeUpdate, onDeactivated, onErrorCaptured, onMounted, onRenderTracked, onRenderTriggered, onScopeDispose, onServerPrefetch, onUnmounted, onUpdated, onWatcherCleanup, PropType, provide, reactive, readonly, ref, Ref, resolveComponent, shallowReactive, shallowReadonly, shallowRef, ShallowRef, Slot, Slots, toRaw, toRef, toRefs, toValue, triggerRef, unref, useAttrs, useCssModule, useCssVars, useId, useModel, useSlots, useTemplateRef, VNode, watch, watchEffect, watchPostEffect, watchSyncEffect, WritableComputedRef } from 'vue'
  export { browser, Browser } from 'wxt/browser'
  export { fakeBrowser } from 'wxt/testing'
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config'
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context'
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  export { AutoMount, AutoMountOptions, ContentScriptAnchoredOptions, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptModalPositioningOptions, ContentScriptOverlayAlignment, ContentScriptOverlayPositioningOptions, ContentScriptPositioningOptions, ContentScriptUi, ContentScriptUiOptions, StopAutoMount } from 'wxt/utils/content-script-ui/types'
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config'
  export { defineBackground } from 'wxt/utils/define-background'
  export { defineContentScript } from 'wxt/utils/define-content-script'
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script'
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin'
  export { injectScript, InjectScriptOptions, ScriptPublicPath } from 'wxt/utils/inject-script'
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns'
  export { MigrationError, storage, StorageArea, StorageAreaChanges, StorageItemKey, WxtStorage, WxtStorageItem } from 'wxt/utils/storage'
}
